using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NameSyncModel {
    [RealtimeProperty(1, true, true)]
    private string _name;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NameSyncModel : IModel {
    // Properties
    public string name {
        get { return _cache.LookForValueInCache(_name, entry => entry.nameSet, entry => entry.name); }
        set { if (value == name) return; _cache.UpdateLocalCache(entry => { entry.nameSet = true; entry.name = value; return entry; }); FireNameDidChange(value); }
    }
    
    // Events
    public delegate void NameDidChange(NameSyncModel model, string value);
    public event         NameDidChange nameDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool   nameSet;
        public string name;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public NameSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireNameDidChange(string value) {
        try {
            if (nameDidChange != null)
                nameDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Name = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _name = name;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteStringLength((uint)PropertyID.Name, _name);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.nameSet)
                    length += WriteStream.WriteStringLength((uint)PropertyID.Name, entry.name);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteString((uint)PropertyID.Name, _name);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.nameSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.nameSet)
                    stream.WriteString((uint)PropertyID.Name, entry.name);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool nameExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.nameSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Name: {
                    string previousValue = _name;
                    
                    _name = stream.ReadString();
                    
                    if (!nameExistsInChangeCache && _name != previousValue)
                        FireNameDidChange(_name);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
